# Generated by Django 6.0 on 2025-12-11 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_department_head_unit_head_alter_staff_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the file, always in uppercase.', max_length=255)),
                ('file_number', models.CharField(blank=True, help_text='Auto-generated file number.', max_length=50, unique=True)),
                ('file_type', models.CharField(choices=[('personal', 'Personal'), ('policy', 'Policy')], default='personal', max_length=10)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('closed', 'Closed')], default='inactive', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_at_location', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('create_file', 'Can create a new file'), ('activate_file', 'Can activate an inactive file'), ('close_file', 'Can close an active file'), ('send_file', 'Can send a file to another user')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('minute_content', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='document_management.file')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'permissions': [('add_minute', 'Can add a minute to a file'), ('add_attachment', 'Can add an attachment to a file')],
            },
        ),
    ]
