# Generated by Django 6.0 on 2026-01-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0003_alter_file_current_location_alter_file_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'permissions': [('create_file', 'Can create a new file'), ('activate_file', 'Can activate an inactive file'), ('close_file', 'Can close an active file'), ('send_file', 'Can send a file to another user'), ('archive_file', 'Can archive a file')]},
        ),
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('pending_activation', 'Pending Activation'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='inactive', max_length=20),
        ),
    ]
