# Generated by Django 6.0 on 2026-02-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0013_file_active_dispatch_document'),
        ('organization', '0005_staffsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signature_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to='organization.staffsignature'),
        ),
    ]
