# Generated by Django 6.0 on 2026-04-12 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0017_filemovement'),
        ('organization', '0005_staffsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemovement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='movement_attachments/'),
        ),
        migrations.AlterField(
            model_name='filemovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_movements', to='organization.staff'),
        ),
        migrations.AlterField(
            model_name='filemovement',
            name='sent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_movements', to='organization.staff'),
        ),
    ]
