# Generated by Django 6.0 on 2026-04-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0019_approvalchain_approvalstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='active_dispatch_document',
        ),
    ]
