# Generated by Django 6.0 on 2026-04-16 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0020_remove_active_dispatch_document'),
        ('organization', '0005_staffsignature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Leave blank for org-wide templates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chain_templates', to='organization.department')),
            ],
        ),
        migrations.CreateModel(
            name='ChainTemplateStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('role_type', models.CharField(choices=[('specific_person', 'Specific Person'), ('unit_manager', 'Unit Manager'), ('hod', 'Head of Department'), ('designation', 'By Designation'), ('director_general', 'Director General')], max_length=30)),
                ('department_scope', models.CharField(blank=True, choices=[('sender', "Sender's Department"), ('specific', 'Specific Department')], default='sender', max_length=20)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.designation')),
                ('specific_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_steps', to='organization.department')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_template_steps', to='organization.staff')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='document_management.chaintemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
