# Generated by Django 6.0 on 2026-04-16 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0021_chain_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalchain',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_chain', to='document_management.document'),
        ),
        migrations.AlterField(
            model_name='approvalchain',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_chains', to='document_management.file'),
        ),
    ]
