# Generated by Django 6.0 on 2026-04-17 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0025_document_status_in_transit_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalchain',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_chains', to='document_management.document'),
        ),
    ]
