# Generated by Django 6.0 on 2026-04-26 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document_management", "0027_movement_close_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="previous_version",
        ),
        migrations.RemoveField(
            model_name="document",
            name="version",
        ),
        migrations.AddField(
            model_name="approvalchain",
            name="reference_file",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional reference to a previously created or dispatched file.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referenced_in_chains",
                to="document_management.file",
            ),
        ),
    ]
