# Generated by Django 6.0 on 2026-04-29 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0031_movement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemovement',
            name='document',
            field=models.ForeignKey(blank=True, help_text='The specific document being sent in this movement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='document_management.document'),
        ),
    ]
