# Generated by Django 6.0 on 2026-07-16 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0040_file_is_sensitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='document_management.file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('pending_approval', 'Pending Approval'), ('pending_activation', 'Pending Activation'), ('active', 'Active'), ('in_transit', 'In Transit'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('archived', 'Archived')], default='pending_approval', max_length=20),
        ),
    ]
