# Generated by Django 6.0 on 2026-09-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0042_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemovement',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="When this movement's granted access expires. Null = indefinite.", null=True),
        ),
    ]
