# Generated by Django 6.0 on 2026-09-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0043_filemovement_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'permissions': [('add_minute', 'Can add a minute to a file'), ('add_attachment', 'Can add an attachment to a file'), ('view_staff_documents', 'Can view staff personnel documents (titles and metadata). Granted to every group except Registry.')]},
        ),
    ]
