# Generated by Django 6.0 on 2026-09-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0047_documentattachment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='chaintemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='chaintemplate',
            name='department',
        ),
        migrations.RemoveField(
            model_name='chaintemplatestep',
            name='template',
        ),
        migrations.RemoveField(
            model_name='chaintemplatestep',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='chaintemplatestep',
            name='specific_department',
        ),
        migrations.RemoveField(
            model_name='chaintemplatestep',
            name='staff',
        ),
        migrations.DeleteModel(
            name='ApprovalChain',
        ),
        migrations.DeleteModel(
            name='ApprovalStep',
        ),
        migrations.DeleteModel(
            name='ChainTemplate',
        ),
        migrations.DeleteModel(
            name='ChainTemplateStep',
        ),
    ]
