# Generated by Django 6.0 on 2026-09-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0049_expire_settled_movement_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='is_sensitive',
        ),
    ]
