# Generated by Django 6.0 on 2026-09-30 13:13

from django.db import migrations, models


def activate_pipeline_files(apps, schema_editor):
    File = apps.get_model("document_management", "File")
    File.objects.filter(status__in=["pending_approval", "pending_activation", "rejected"]).update(
        status="active"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0050_remove_file_is_sensitive'),
    ]

    operations = [
        migrations.RunPython(activate_pipeline_files, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('in_transit', 'In Transit'), ('in_review', 'In Review'), ('closed', 'Closed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
