# Generated by Django 6.0 on 2026-10-02 15:02

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def assert_no_duplicate_personal_files(apps, schema_editor):
    """Fail with a readable message if any Staff already owns 2+ personal files.

    Without this, AddConstraint would raise a bare IntegrityError mid-migration.
    """
    File = apps.get_model("document_management", "File")
    Staff = apps.get_model("organization", "Staff")

    duplicate_owner_ids = [
        row["owner_id"]
        for row in (
            File.objects.filter(file_type="personal", owner__isnull=False)
            .values("owner_id")
            .annotate(n=Count("id"))
            .filter(n__gt=1)
        )
    ]
    if not duplicate_owner_ids:
        return

    owners = ", ".join(
        f"{username} (staff #{pk})"
        for pk, username in Staff.objects.filter(pk__in=duplicate_owner_ids).values_list(
            "pk", "user__username"
        )
    )
    raise RuntimeError(
        "Cannot enforce one-personal-file-per-staff: these staff members own more "
        f"than one personal file: {owners}. Delete or merge the duplicate personal "
        "files first, then run migrations again."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0051_alter_file_status'),
        ('organization', '0012_auto_verify_existing_signatures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(assert_no_duplicate_personal_files, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('file_type', 'personal')), fields=('owner',), name='unique_personal_file_per_owner'),
        ),
    ]
