# Generated by Django 6.0 on 2026-10-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0052_file_unique_personal_file_per_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='preview_pdf',
            field=models.FileField(blank=True, help_text='Auto-generated PDF preview for Office documents (DOCX, etc.).', null=True, upload_to='document_previews/'),
        ),
    ]
