# Generated by Django 6.0 on 2026-10-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0053_document_preview_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemovement',
            name='transit_alert_first_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filemovement',
            name='transit_alert_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
