# Generated by Django 6.0 on 2026-01-05 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('LOGIN', 'User Logged In'), ('LOGOUT', 'User Logged Out'), ('LOGIN_FAILED', 'User Login Failed'), ('PASSWORD_CHANGED', 'User Password Changed'), ('ACCOUNT_LOCKED', 'User Account Locked'), ('ACCOUNT_UNLOCKED', 'User Account Unlocked'), ('FILE_CREATED', 'File Created'), ('FILE_UPDATED', 'File Updated'), ('FILE_ACTIVATED', 'File Activated'), ('FILE_CLOSED', 'File Closed'), ('FILE_ARCHIVED', 'File Archived'), ('FILE_SENT', 'File Sent'), ('DOCUMENT_ADDED', 'Document Added'), ('DOCUMENT_UPDATED', 'Document Updated'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
