# Generated by Django 6.0 on 2026-01-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_department_head_unit_head_alter_staff_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('locum', 'Locum'), ('contract', 'Contract'), ('nysc', 'NYSC')], default='permanent', max_length=20),
        ),
    ]
