# Generated by Django 6.0 on 2026-04-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0005_staffsignature"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="is_supervisor",
            field=models.BooleanField(default=False, help_text="Designates this staff member as a supervisor."),
        ),
    ]
