# Generated by Django 6.0 on 2026-05-12 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0009_division_head_section_head"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="division",
        ),
        migrations.AddField(
            model_name="section",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="organization.department",
            ),
        ),
    ]
