# Generated by Django 6.0 on 2026-09-30 11:13

from django.db import migrations


def auto_verify_existing_signatures(apps, schema_editor):
    StaffSignature = apps.get_model("organization", "StaffSignature")
    StaffSignature.objects.filter(is_verified=False).update(is_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0011_alter_section_department"),
    ]

    operations = [
        migrations.RunPython(auto_verify_existing_signatures, migrations.RunPython.noop),
    ]
