# Generated by Django 6.0 on 2026-01-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_assign_mvp_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
