# Generated by Django 6.0 on 2026-01-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_passwordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
