# Generated by Django 6.0 on 2026-06-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_add_user_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_set_urgent_priority', 'Can mark documents as Urgent or High Priority')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
