# Generated by Django 6.0 on 2026-07-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0014_add_can_set_urgent_priority_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_set_urgent_priority', 'Can mark documents as Urgent or High Priority'), ('can_share_documents', 'Can share documents with other users')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
