# Generated by Django 6.0 on 2026-10-02 16:24

from django.db import migrations

GLOBAL_VIEW_GROUP_NAMES = ("MD", "Executives", "Administrator")


def grant_global_view_permission(apps, schema_editor):
    """Give the oversight groups global staff-file visibility.

    MD / Executives are meant to see every file regardless of department
    (see can_view_file / can_view_document_content standing access); the
    explicit permission makes that grantable to any user or group from the
    admin — including people who belong to no department at all.
    """
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # post_migrate (which normally creates Permission rows) only runs AFTER
    # all migrations, so create the row ourselves to grant it here.
    ct, _ = ContentType.objects.get_or_create(app_label="user_management", model="customuser")
    perm, _ = Permission.objects.get_or_create(
        content_type=ct,
        codename="can_view_all_staff_files",
        defaults={
            "name": "Can view all staff files and personnel records regardless of department or custody"
        },
    )

    for group_name in GLOBAL_VIEW_GROUP_NAMES:
        group, _ = Group.objects.get_or_create(name=group_name)
        group.permissions.add(perm)


def revoke_global_view_permission(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    ct, _ = ContentType.objects.get_or_create(app_label="user_management", model="customuser")
    perm = Permission.objects.filter(
        content_type=ct, codename="can_view_all_staff_files"
    ).first()
    if perm is None:
        return
    for group in Group.objects.filter(name__in=GLOBAL_VIEW_GROUP_NAMES):
        group.permissions.remove(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0015_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_set_urgent_priority', 'Can mark documents as Urgent or High Priority'), ('can_share_documents', 'Can share documents with other users'), ('can_view_all_staff_files', 'Can view all staff files and personnel records regardless of department or custody')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RunPython(grant_global_view_permission, revoke_global_view_permission),
    ]
