# Generated by Django 6.0 on 2026-10-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0021_rework_document_approval_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_set_urgent_priority', 'Can mark documents as Urgent or High Priority'), ('can_share_documents', 'Can share documents with other users'), ('can_view_all_staff_files', 'Can view all staff files and personnel records regardless of department or custody'), ('can_request_file_access', 'Can request Read-Only access to files'), ('can_request_file_access_rw', 'Can request Read & Write access to files'), ('can_approve_file_access', 'Can approve or reject file access requests'), ('can_manage_registry', 'Can perform Registry operations (create files, manage lifecycle, approve access)'), ('can_create_file', 'Can create new files'), ('can_manage_file_lifecycle', 'Can activate, close and archive files'), ('can_view_file', 'Can view file details (subject to custody/scope)'), ('can_view_file_content', 'Can view document contents (subject to custody/scope)'), ('can_add_document', 'Can add a document/minute to a file'), ('can_dispatch_document', 'Can dispatch or forward a document to another staff member'), ('can_delete_document', 'Can delete a document'), ('can_approve_document', 'Can approve or reject documents'), ('can_edit_staff_documents', "Can edit any staff member's documents regardless of ownership (assigned manually)"), ('can_supervise', 'Can supervise staff (HOD, head of unit/section/division, or flagged supervisor)'), ('can_executive', 'Has executive/MD level access across departments'), ('can_head_department', 'Heads a department (HOD scope)'), ('can_head_unit', 'Heads a unit (head-of-unit scope)')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
